app: vjepa_cpt
cpus_per_task: 16
folder: logs/cpt_vitl-256px-16f_100epoch
mem_per_gpu: 220G
nodes: 1
tasks_per_node: 1
data:
  dataset_type: surgical_videodataset
  datasets:
  
  ## skills dataset
  - data/Surge_Frames/AIxsuture/clips_64f/train_dense_64f_detailed.csv
  - data/Surge_Frames/JIGSAWS/clips_64f/train_dense_64f_detailed.csv

  ## Landscope dataset
  - data/Surge_Frames/AutoLaparo/clips_64f/train_dense_64f_detailed.csv
  - data/Surge_Frames/Cholec80/clips_64f/train_dense_64f_detailed.csv
  - data/Surge_Frames/BernBypass70/clips_64f/train_dense_64f_detailed.csv
  - data/Surge_Frames/StrasBypass70/clips_64f/train_dense_64f_detailed.csv
  - data/Surge_Frames/PmLR50/clips_64f/train_dense_64f_detailed.csv
  
  ### Open surgery dataset
  - data/Surge_Frames/EgoSurgery/clips_64f/train_dense_64f_detailed.csv
  - data/Surge_Frames/AVOS/clips_64f/train_dense_64f_detailed.csv
  
  ### Ophthalmology dataset
  - data/Surge_Frames/CATARACTS/clips_64f/train_dense_64f_detailed.csv
  - data/Surge_Frames/OphNet2024_phase/clips_64f/train_dense_64f_detailed.csv
  
  ### Gastrointestinal dataset
  - data/Surge_Frames/EndoFM_Private/clips_64f/unlabeled_dense_64f_detailed.csv
  - data/Surge_Frames/EndoFM_Colonoscopic/clips_64f/unlabeled_dense_64f_detailed.csv
  
  ### NeuroSurgery dataset
  - data/Surge_Frames/PitVis/clips_64f/train_dense_64f_detailed.csv
  - data/Surge_Frames/Private_PWH_TSS_79/clips_64f/unlabeled_dense_64f_detailed.csv
  - data/Surge_Frames/Private_PUMCH/clips_64f/unlabeled_dense_64f_detailed.csv
  - data/Surge_Frames/Private_HKU-TSS/clips_64f/unlabeled_dense_64f_detailed.csv


  datasets_weights:
  - 0.50
  - 0.50

  - 0.20
  - 0.20
  - 0.20
  - 0.20
  - 0.20

  - 0.50
  - 0.50

  - 0.50
  - 0.50

  - 0.50
  - 0.50

  - 0.25
  - 0.25
  - 0.25
  - 0.25


  batch_size: 32
  crop_size: 256
  dataset_fpcs:
  - 16
  - 16

  - 16
  - 16
  - 16
  - 16
  - 16

  - 16
  - 16
  
  - 16
  - 16
  
  - 16
  - 16
  
  - 16
  - 16
  - 16
  - 16

  fps: 1
  num_workers: 4
  patch_size: 16
  persistent_workers: true
  pin_mem: true
  tubelet_size: 2

data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
loss:
  loss_exp: 1.0
mask:
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 8
  spatial_scale:
  - 0.15
  - 0.15
  temporal_scale:
  - 1.0
  - 1.0
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 2
  spatial_scale:
  - 0.7
  - 0.7
  temporal_scale:
  - 1.0
  - 1.0
meta:
  dtype: bfloat16
  eval_freq: 100
  load_checkpoint: false
  read_checkpoint: None
  save_every_freq: 5
  seed: 239
  use_sdpa: true
model:
  model_name: vit_giant
  pred_depth: 12
  pred_embed_dim: 384
  pred_num_heads: 12
  uniform_power: true
  use_activation_checkpointing: true
  use_mask_tokens: true
  use_rope: true
  zero_init_mask_tokens: true
  cpt_ckeckpoint: ckpts/vitg.pt 
optimization:
  anneal_ckpt: None
  ema:
  - 0.99925
  - 0.99925
  epochs: 100
  final_lr: 0.000525
  final_weight_decay: 0.04
  ipe: 300
  ipe_scale: 1.25
  lr: 0.000525
  start_lr: 0.0001
  warmup: 40
  weight_decay: 0.04
