cpus_per_task: 4
eval_name: foundation_phase_probing
folder: logs/foundation/endossl_vitl_laparo_PitVis
mem_per_gpu: 220G
nodes: 1
max_workers: 4
resume_checkpoint: true
tag: endossl_vitl_laparo_64f_PitVis_eval_tss
tasks_per_node: 1
eval_checkpoint: /home/projects/med-multi-llm/chuxi_chen/NSJepa/logs/foundation/endossl_vitl_laparo_PitVis/video_classification_frozen/endossl_vitl_laparo_64f_PitVis/latest.pt

# wandb configuration
wandb:
  project: foundation-model-probing
  entity: nsjepa
  name: endossl_vitl_laparo_64f_PitVis_eval_tss
  tags:
    - PitVis
    - phase-probing
    - endossl-vitl_laparo-64f
    - eval-tss
  group: null
  notes: "Evaluation on tss dataset using PitVis trained checkpoint"

experiment:
  classifier:
    num_heads: 16
    num_probe_blocks: 4
  data:
    dataset_type:  surgical_videodataset
    dataset_train: data/Surge_Frames/PitVis/clips_64f/train_dense_64f_detailed.csv
    dataset_val: data_local/PitVis_Eval_Profiles/clips_64f/profile_pitvis_tss_all_private.csv
    frames_per_clip: 64
    num_classes: 15
    num_segments: 1
    num_views_per_segment: 1
    resolution: 224

  optimization:
    batch_size: 4
    multihead_kwargs:
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.005
      start_lr: 0.005
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.003
      start_lr: 0.003
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.001
      start_lr: 0.001
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.0003
      start_lr: 0.0003
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.01
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.01
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.005
      start_lr: 0.005
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.003
      start_lr: 0.003
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.001
      start_lr: 0.001
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.0003
      start_lr: 0.0003
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.1
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.1
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.005
      start_lr: 0.005
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.003
      start_lr: 0.003
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.001
      start_lr: 0.001
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.0003
      start_lr: 0.0003
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.4
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.4
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.005
      start_lr: 0.005
      warmup: 0.0
      weight_decay: 0.8
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.003
      start_lr: 0.003
      warmup: 0.0
      weight_decay: 0.8
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.001
      start_lr: 0.001
      warmup: 0.0
      weight_decay: 0.8
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.0003
      start_lr: 0.0003
      warmup: 0.0
      weight_decay: 0.8
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.8
    num_epochs: 1
    use_bfloat16: true
    use_pos_embed: false

model_kwargs:
  checkpoint: null
  module_name: evals.foundation_phase_probing.modelcustom.foundation_model_wrapper
  model_type: endossl
  encoder:
    model_name: endossl_laparo
  wrapper_kwargs:
    tubelet_size: 2
    max_frames: 128
    use_pos_embed: true

