#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AutoLaparo End-to-End Preprocessing Pipeline
---------------------------------------------
Data layout (expected):
  - Raw videos (optional): ``<videos_dir>/*.mp4``
  - Frames (already extracted or to be extracted, e.g. 1 fps):
    ``<frames_root>/XX/XX_XXXXXXXX.jpg`` where ``XX`` is zero-padded case id (01-21).
  - Per-frame phase labels: ``<labels_root>/label_XX.txt``
    (whitespace-separated columns: ``Frame``, ``Phase`` with ``Phase`` in 1-7).

Pipeline Steps:
  1. [Optional] Extract frames from videos (--step frames or --step all)
  2. Build frame-level metadata CSV with columns:
     Case_ID, Frame_Path, Phase_GT, Phase_Name
  3. Generate dense sliding-window clips (--step clips or --step all)

Output structure:
  <output_dir>/
    clip_infos/                    # One txt per video listing all frames
    train_metadata.csv             # Frame-level metadata
    val_metadata.csv
    test_metadata.csv
    clips_64f/                     # Dense clips (generated by gen_clips)
      train_dense_64f_detailed.csv
      val_dense_64f_detailed.csv
      test_dense_64f_detailed.csv
      clip_dense_64f_info/train/*.txt
      clip_dense_64f_info/val/*.txt
      clip_dense_64f_info/test/*.txt

Usage:
    # Full pipeline (metadata + dense clips)
    python autolaparo_prepare.py --step all

    # Only build frame-level metadata
    python autolaparo_prepare.py --step metadata

    # Only generate dense clips (requires existing metadata)
    python autolaparo_prepare.py --step clips --window_size 64
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd
from tqdm import tqdm

from gen_clips import generate_dense_clips

# Train / val / test split by case id
TRAIN_CASE_IDS = list(range(1, 11))   # 1-10
VAL_CASE_IDS = list(range(11, 15))    # 11-14
TEST_CASE_IDS = list(range(15, 22))   # 15-21

PHASE_ID_TO_NAME: Dict[int, str] = {
    0: "Preparation",
    1: "Dividing Ligament and Peritoneum",
    2: "Dividing Uterine Vessels and Ligament",
    3: "Transecting the Vagina",
    4: "Specimen Removal",
    5: "Suturing",
    6: "Washing",
}


def split_for_case(case_id: int) -> Optional[str]:
    """Return split name for a given case id."""
    if case_id in TRAIN_CASE_IDS:
        return "train"
    if case_id in VAL_CASE_IDS:
        return "val"
    if case_id in TEST_CASE_IDS:
        return "test"
    return None


def videos_to_frames(
    input_path: Path,
    output_path: Path,
    fps: int = 1,
    debug: bool = False,
) -> None:
    """
    Extract frames from all ``*.mp4`` under ``input_path`` into ``output_path``.
    Output: ``output_path/<video_stem>/<video_stem>_%05d.jpg``.
    """
    input_path = Path(input_path)
    output_path = Path(output_path)
    output_path.mkdir(parents=True, exist_ok=True)
    video_files = sorted(input_path.glob("*.mp4"))

    if not video_files:
        print(f"[WARN] No mp4 videos found in {input_path}.")
        return

    print(f"\n[INFO] Found {len(video_files)} videos, extracting frames at {fps} fps...")
    failed: List[str] = []

    for vid_path in tqdm(video_files, desc="Extracting frames"):
        vid_id = vid_path.stem
        out_folder = output_path / vid_id
        out_folder.mkdir(parents=True, exist_ok=True)
        output_pattern = out_folder / f"{vid_id}_%08d.jpg"

        ffmpeg_cmd = [
            "ffmpeg", "-y", "-i", str(vid_path.resolve()),
            "-vf", f"fps={fps},scale=512:-1:flags=bicubic",
            "-vsync", "2", "-qscale:v", "2",
            str(output_pattern),
        ]

        if debug:
            print(f"[DEBUG] FFmpeg: {' '.join(ffmpeg_cmd)}")

        try:
            subprocess.run(ffmpeg_cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        except subprocess.CalledProcessError as e:
            print(f"[ERROR] Frame extraction failed: {vid_path}")
            if debug and e.stderr:
                print(e.stderr.decode("utf-8", errors="ignore")[:500])
            failed.append(str(vid_path))

    print(f"[INFO] Frame extraction finished.")
    if failed:
        fail_log = output_path / "failed_videos.txt"
        fail_log.write_text("\n".join(failed), encoding="utf-8")
        print(f"[WARN] {len(failed)} videos failed; see {fail_log}")


def generate_clip_txt(video_frames_dir: Path, txt_path: Path) -> List[str]:
    """
    Write one line per frame path for a single case directory.
    Returns list of frame paths (sorted by filename).
    """
    frame_files = sorted(
        (p for p in video_frames_dir.iterdir() if p.is_file() and p.suffix.lower() in (".jpg", ".png")),
        key=lambda p: p.name,
    )
    txt_path.parent.mkdir(parents=True, exist_ok=True)
    with txt_path.open("w", encoding="utf-8") as f:
        for frame_path in frame_files:
            f.write(str(frame_path).replace("\\", "/") + "\n")
    return [str(fp).replace("\\", "/") for fp in frame_files]


def _read_label_table(label_path: Path) -> pd.DataFrame:
    """Load Frame / Phase from a label txt (whitespace-separated)."""
    df = pd.read_csv(label_path, sep=r"\s+", engine="python")
    if "Frame" not in df.columns or "Phase" not in df.columns:
        raise ValueError(f"Expected columns Frame, Phase in {label_path}, got {list(df.columns)}")
    return df


def build_frame_level_metadata(
    frames_root: Path,
    labels_root: Path,
    output_dir: Path,
    debug: bool = False,
) -> Dict[str, pd.DataFrame]:
    """
    Build frame-level metadata with columns: Case_ID, Frame_Path, Phase_GT, Phase_Name.
    Returns dict of DataFrames keyed by split name.
    """
    clip_infos_dir = output_dir / "clip_infos"
    clip_infos_dir.mkdir(parents=True, exist_ok=True)

    label_files = sorted(labels_root.glob("label_*.txt"))
    if not label_files:
        print(f"[WARN] No label_*.txt files under {labels_root}")

    by_split: Dict[str, List[dict]] = {"train": [], "val": [], "test": []}

    for label_path in tqdm(label_files, desc="Building frame-level metadata"):
        stem = label_path.stem  # e.g. label_01
        try:
            case_id = int(stem.split("_")[-1])
        except ValueError:
            print(f"[WARN] Cannot parse case id from {label_path.name}, skip.")
            continue

        split_name = split_for_case(case_id)
        if split_name is None:
            if debug:
                print(f"[DEBUG] Case {case_id} not in train/val/test ranges, skip.")
            continue

        case_folder_name = f"{case_id:02d}"
        frames_dir = frames_root / case_folder_name
        if not frames_dir.is_dir():
            print(f"[WARN] Frames directory missing: {frames_dir}, skip case {case_id}.")
            continue

        try:
            label_df = _read_label_table(label_path)
        except Exception as e:
            print(f"[WARN] Failed to read {label_path}: {e}")
            continue

        txt_path = clip_infos_dir / f"{case_folder_name}.txt"
        frame_paths = generate_clip_txt(frames_dir, txt_path)
        if not frame_paths:
            print(f"[WARN] No frames in {frames_dir}, skip case {case_id}.")
            continue

        frame_to_path = {}
        for fp in frame_paths:
            fname = Path(fp).stem
            parts = fname.split("_")
            if len(parts) >= 2:
                try:
                    frame_num = int(parts[-1])
                    frame_to_path[frame_num] = fp
                except ValueError:
                    pass

        for _, row in label_df.iterrows():
            frame_num = int(row["Frame"])
            phase_raw = int(row["Phase"])
            phase_0_6 = phase_raw - 1

            if phase_0_6 not in PHASE_ID_TO_NAME:
                if debug:
                    print(f"[DEBUG] Case {case_id}: skip unknown Phase {phase_raw}")
                continue

            if frame_num not in frame_to_path:
                if debug:
                    print(f"[DEBUG] Case {case_id}: frame {frame_num} not on disk")
                continue

            by_split[split_name].append({
                "Case_ID": case_id,
                "Frame_Path": frame_to_path[frame_num],
                "Phase_GT": phase_0_6,
                "Phase_Name": PHASE_ID_TO_NAME[phase_0_6],
            })

    result = {}
    for split_name, rows in by_split.items():
        if rows:
            df = pd.DataFrame(rows)
            df = df.sort_values(["Case_ID", "Frame_Path"]).reset_index(drop=True)
            result[split_name] = df
        else:
            result[split_name] = pd.DataFrame(columns=["Case_ID", "Frame_Path", "Phase_GT", "Phase_Name"])

    return result


def save_metadata_csvs(output_dir: Path, metadata_by_split: Dict[str, pd.DataFrame]) -> None:
    """Save frame-level metadata CSVs."""
    for split_name, df in metadata_by_split.items():
        path = output_dir / f"{split_name}_metadata.csv"
        if len(df) == 0:
            print(f"[WARN] No rows for split '{split_name}', skip writing {path.name}.")
            continue
        df.to_csv(path, index=False)
        print(f"[INFO] Saved {len(df)} frame rows to {path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="AutoLaparo: End-to-end preprocessing pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Full pipeline: metadata + dense clips
    python autolaparo_prepare.py --step all

    # Extract frames first (if needed)
    python autolaparo_prepare.py --step frames --videos_dir /path/to/videos

    # Only build frame-level metadata
    python autolaparo_prepare.py --step metadata

    # Only generate dense clips (requires existing metadata)
    python autolaparo_prepare.py --step clips --window_size 64
        """,
    )
    parser.add_argument(
        "--step",
        choices=["all", "frames", "metadata", "clips"],
        default="all",
        help="Pipeline step to run (default: all)",
    )
    parser.add_argument(
        "--videos_dir",
        type=str,
        default="data/Landscopy/autolaparo/task1/videos",
        help="Directory containing raw mp4 videos (for --step frames)",
    )
    parser.add_argument(
        "--frames_root",
        type=str,
        default="data/Surge_Frames/AutoLaparo/frames",
        help="Root directory of per-case frame folders",
    )
    parser.add_argument(
        "--labels_root",
        type=str,
        default="data/Landscopy/autolaparo/task1/labels",
        help="Directory containing label_XX.txt files",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="data/Surge_Frames/AutoLaparo",
        help="Output directory for metadata and clips",
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=1,
        help="FPS for frame extraction (default: 1)",
    )
    parser.add_argument(
        "--window_size",
        type=int,
        default=64,
        help="Window size for dense clip generation (default: 64)",
    )
    parser.add_argument(
        "--stride",
        type=int,
        default=1,
        help="Stride for dense clip generation (default: 1)",
    )
    parser.add_argument(
        "--no_padding",
        action="store_true",
        help="Disable padding for incomplete windows",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable verbose debug output",
    )
    args = parser.parse_args()

    frames_root = Path(args.frames_root)
    labels_root = Path(args.labels_root)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("AutoLaparo Preprocessing Pipeline")
    print("=" * 60)

    if args.step in ("frames"):
        print("\n[STEP 1] Extracting frames from videos...")
        videos_dir = Path(args.videos_dir)
        if videos_dir.exists():
            videos_to_frames(videos_dir, frames_root, fps=args.fps, debug=args.debug)
        else:
            print(f"[SKIP] Videos directory not found: {videos_dir}")
            print("[INFO] Assuming frames are already extracted.")

    if args.step in ("all", "metadata"):
        print("\n[STEP 2] Building frame-level metadata...")
        metadata_by_split = build_frame_level_metadata(
            frames_root=frames_root,
            labels_root=labels_root,
            output_dir=output_dir,
            debug=args.debug,
        )
        save_metadata_csvs(output_dir, metadata_by_split)

    if args.step in ("all", "clips"):
        print(f"\n[STEP 3] Generating dense clips (window_size={args.window_size})...")
        generate_dense_clips(
            base_data_path=str(output_dir),
            window_size=args.window_size,
            stride=args.stride,
            fps=args.fps,
            enable_padding=not args.no_padding,
        )

    print("\n" + "=" * 60)
    print("AutoLaparo preprocessing complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
