#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Cholec80 End-to-End Preprocessing Pipeline
-------------------------------------------
Dataset layout (expected on disk):
  - Raw videos (optional): ``<videos_dir>/*.mp4``
  - Phase annotations at 25 fps (tab-separated ``Frame<TAB>Phase``):
    ``<annot_dir>/videoXX-phase.txt`` for video01 to video80.
  - Frames (already extracted or to be extracted at 1 fps):
    ``<frames_root>/videoXX/*.jpg``

Pipeline Steps:
  1. [Optional] Extract frames from videos (--step frames or --step all)
  2. Build frame-level metadata CSV with columns:
     Case_ID, Frame_Path, Phase_GT, Phase_Name
  3. Generate dense sliding-window clips (--step clips or --step all)

Output structure:
  <output_dir>/
    clip_infos/                    # One txt per video listing all frames
    train_metadata.csv             # Frame-level metadata (videos 1-40)
    test_metadata.csv              # Frame-level metadata (videos 41-80)
    val_metadata.csv               # Copy of test for compatibility
    clips_64f/                     # Dense clips (generated by gen_clips)
      train_dense_64f_detailed.csv
      val_dense_64f_detailed.csv
      test_dense_64f_detailed.csv
      clip_dense_64f_info/{train,val,test}/*.txt

Usage:
    # Full pipeline (metadata + dense clips)
    python cholect80_prepare.py --step all

    # Only build frame-level metadata
    python cholect80_prepare.py --step metadata

    # Only generate dense clips (requires existing metadata)
    python cholect80_prepare.py --step clips --window_size 64
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd
from tqdm import tqdm

from gen_clips import generate_dense_clips

# Original annotation sampling rate
FPS_ORIG = 25

# Phase name -> class id (Cholec80 seven phases)
PHASE_TO_ID: Dict[str, int] = {
    "Preparation": 0,
    "CalotTriangleDissection": 1,
    "ClippingCutting": 2,
    "GallbladderDissection": 3,
    "GallbladderPackaging": 4,
    "CleaningCoagulation": 5,
    "GallbladderRetraction": 6,
}

ID_TO_PHASE: Dict[int, str] = {v: k for k, v in PHASE_TO_ID.items()}


def _split_for_case(case_num: int) -> Optional[str]:
    """Return split name: train (1-40), test (41-80), or None if out of range."""
    if 1 <= case_num <= 40:
        return "train"
    if 41 <= case_num <= 80:
        return "test"
    return None


def _parse_phase_annotation_path(path: Path) -> Optional[Tuple[str, int]]:
    """Parse videoXX-phase.txt into (case_folder_name, case_num)."""
    name = path.name
    if not name.endswith("-phase.txt"):
        return None
    stem = name[:-len("-phase.txt")]
    if not stem.startswith("video"):
        return None
    try:
        case_num = int(stem[len("video"):])
    except ValueError:
        return None
    return stem, case_num


def videos_to_frames(
    input_path: Path,
    output_path: Path,
    fps: int = 1,
    debug: bool = False,
) -> None:
    """
    Extract frames from all *.mp4 under input_path into output_path.
    Output: output_path/videoXX/videoXX_%08d.jpg
    """
    input_path = Path(input_path)
    output_path = Path(output_path)
    output_path.mkdir(parents=True, exist_ok=True)
    video_files = sorted(input_path.glob("*.mp4"))

    if not video_files:
        print(f"[WARN] No mp4 videos found under {input_path}.")
        return

    print(f"\n[INFO] Found {len(video_files)} videos, extracting frames at {fps} fps...")
    failed: List[str] = []

    for vid_path in tqdm(video_files, desc="Extracting frames"):
        vid_id = vid_path.stem
        out_folder = output_path / vid_id
        out_folder.mkdir(parents=True, exist_ok=True)
        pattern = out_folder / f"{vid_id}_%08d.jpg"

        cmd = [
            "ffmpeg", "-y", "-i", str(vid_path.resolve()),
            "-vf", f"fps={fps},scale=512:-1:flags=bicubic",
            "-vsync", "2", "-qscale:v", "2",
            str(pattern),
        ]

        if debug:
            print(f"[DEBUG] FFmpeg: {' '.join(cmd)}")

        try:
            subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        except subprocess.CalledProcessError as e:
            print(f"[ERROR] Failed: {vid_path}")
            if debug and e.stderr:
                print(e.stderr.decode("utf-8", errors="ignore")[:500])
            failed.append(str(vid_path))

    print(f"[INFO] Frame extraction finished.")
    if failed:
        log = output_path / "failed_videos.txt"
        log.write_text("\n".join(failed), encoding="utf-8")
        print(f"[WARN] {len(failed)} videos failed; see {log}")


def _sorted_jpeg_paths(video_frames_dir: Path) -> List[Path]:
    """Return sorted .jpg/.jpeg paths under a case frame directory."""
    return sorted(
        (p for p in video_frames_dir.iterdir()
         if p.is_file() and p.suffix.lower() in (".jpg", ".jpeg")),
        key=lambda p: p.name,
    )


def generate_clip_txt(video_frames_dir: Path, txt_path: Path) -> List[str]:
    """
    Write all JPEG frame paths to txt_path.
    Returns list of frame paths (POSIX-style slashes).
    """
    frame_files = _sorted_jpeg_paths(video_frames_dir)
    txt_path.parent.mkdir(parents=True, exist_ok=True)
    frame_paths = [str(fp).replace("\\", "/") for fp in frame_files]
    with txt_path.open("w", encoding="utf-8") as f:
        for fp in frame_paths:
            f.write(fp + "\n")
    return frame_paths


def build_frame_level_metadata(
    frames_root: Path,
    annot_dir: Path,
    output_dir: Path,
    fps_target: int = 1,
    debug: bool = False,
) -> Dict[str, pd.DataFrame]:
    """
    Build frame-level metadata with columns: Case_ID, Frame_Path, Phase_GT, Phase_Name.
    Returns dict of DataFrames keyed by split name.
    """
    if FPS_ORIG % fps_target != 0:
        raise ValueError(
            f"fps_target={fps_target} must divide FPS_ORIG={FPS_ORIG}"
        )
    step = FPS_ORIG // fps_target

    clip_infos_dir = output_dir / "clip_infos"
    clip_infos_dir.mkdir(parents=True, exist_ok=True)

    annot_paths = sorted(annot_dir.glob("video*-phase.txt"))

    by_split: Dict[str, List[dict]] = {"train": [], "test": []}

    for annot_path in tqdm(annot_paths, desc="Building frame-level metadata"):
        parsed = _parse_phase_annotation_path(annot_path)
        if parsed is None:
            if debug:
                print(f"[DEBUG] Skip unexpected annotation file: {annot_path.name}")
            continue

        case_name, case_num = parsed
        split = _split_for_case(case_num)
        if split is None:
            if debug:
                print(f"[DEBUG] Skip {case_name}: case id outside train/test range.")
            continue

        df = pd.read_csv(annot_path, sep="\t")
        df.columns = [str(c).strip() for c in df.columns]
        if "Phase" not in df.columns:
            print(f"[WARN] 'Phase' column missing in {annot_path}")
            continue

        n_ann = len(df)
        if n_ann == 0:
            print(f"[WARN] Empty annotations: {annot_path}")
            continue

        video_frames_dir = frames_root / case_name
        if not video_frames_dir.is_dir():
            print(f"[WARN] Missing frame directory: {video_frames_dir}")
            continue

        clip_txt = clip_infos_dir / f"{case_name}.txt"
        frame_paths = generate_clip_txt(video_frames_dir, clip_txt)
        if not frame_paths:
            print(f"[WARN] No frames in {video_frames_dir}")
            continue

        for frame_i, frame_path in enumerate(frame_paths):
            row_idx = min(frame_i * step, n_ann - 1)
            phase_name = str(df.iloc[row_idx]["Phase"]).strip()
            label = PHASE_TO_ID.get(phase_name, -1)

            by_split[split].append({
                "Case_ID": case_num,
                "Frame_Path": frame_path,
                "Phase_GT": label,
                "Phase_Name": phase_name,
            })

    result = {}
    for split_name, rows in by_split.items():
        if rows:
            df = pd.DataFrame(rows)
            df = df.sort_values(["Case_ID", "Frame_Path"]).reset_index(drop=True)
            result[split_name] = df
        else:
            result[split_name] = pd.DataFrame(
                columns=["Case_ID", "Frame_Path", "Phase_GT", "Phase_Name"]
            )

    return result


def save_metadata_csvs(output_dir: Path, metadata_by_split: Dict[str, pd.DataFrame]) -> None:
    """Save frame-level metadata CSVs."""
    for split_name, df in metadata_by_split.items():
        path = output_dir / f"{split_name}_metadata.csv"
        if len(df) == 0:
            print(f"[WARN] No rows for split '{split_name}', skip writing {path.name}.")
            continue
        df.to_csv(path, index=False)
        print(f"[INFO] Saved {len(df)} frame rows to {path}")

    train_path = output_dir / "train_metadata.csv"
    test_path = output_dir / "test_metadata.csv"
    val_path = output_dir / "val_metadata.csv"

    if test_path.exists() and not val_path.exists():
        shutil.copy(test_path, val_path)
        print(f"[INFO] Copied test_metadata.csv to val_metadata.csv for compatibility")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Cholec80: End-to-end preprocessing pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Full pipeline: metadata + dense clips
    python cholect80_prepare.py --step all

    # Extract frames first (if needed)
    python cholect80_prepare.py --step frames --videos_dir /path/to/videos

    # Only build frame-level metadata
    python cholect80_prepare.py --step metadata

    # Only generate dense clips (requires existing metadata)
    python cholect80_prepare.py --step clips --window_size 64
        """,
    )
    parser.add_argument(
        "--step",
        choices=["all", "frames", "metadata", "clips"],
        default="all",
        help="Pipeline step to run (default: all)",
    )
    parser.add_argument(
        "--videos_dir",
        type=str,
        default="data/Landscopy/cholec80/videos",
        help="Directory containing raw mp4 videos (for --step frames)",
    )
    parser.add_argument(
        "--frames_root",
        type=str,
        default="data/Surge_Frames/Cholec80/frames",
        help="Root folder containing per-video frame directories",
    )
    parser.add_argument(
        "--annot_dir",
        type=str,
        default="data/Landscopy/cholec80/phase_annotations",
        help="Directory with videoXX-phase.txt annotation files",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="data/Surge_Frames/Cholec80",
        help="Output directory for metadata and clips",
    )
    parser.add_argument(
        "--fps",
        type=int,
        default=1,
        help="FPS for frame extraction (default: 1)",
    )
    parser.add_argument(
        "--window_size",
        type=int,
        default=64,
        help="Window size for dense clip generation (default: 64)",
    )
    parser.add_argument(
        "--stride",
        type=int,
        default=1,
        help="Stride for dense clip generation (default: 1)",
    )
    parser.add_argument(
        "--no_padding",
        action="store_true",
        help="Disable padding for incomplete windows",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable verbose debug output",
    )
    args = parser.parse_args()

    frames_root = Path(args.frames_root)
    annot_dir = Path(args.annot_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 60)
    print("Cholec80 Preprocessing Pipeline")
    print("=" * 60)

    if args.step in ("all", "frames"):
        print("\n[STEP 1] Extracting frames from videos...")
        videos_dir = Path(args.videos_dir)
        if videos_dir.exists():
            videos_to_frames(videos_dir, frames_root, fps=args.fps, debug=args.debug)
        else:
            print(f"[SKIP] Videos directory not found: {videos_dir}")
            print("[INFO] Assuming frames are already extracted.")

    if args.step in ("all", "metadata"):
        print("\n[STEP 2] Building frame-level metadata...")
        metadata_by_split = build_frame_level_metadata(
            frames_root=frames_root,
            annot_dir=annot_dir,
            output_dir=output_dir,
            fps_target=args.fps,
            debug=args.debug,
        )
        save_metadata_csvs(output_dir, metadata_by_split)

    if args.step in ("all", "clips"):
        print(f"\n[STEP 3] Generating dense clips (window_size={args.window_size})...")
        generate_dense_clips(
            base_data_path=str(output_dir),
            window_size=args.window_size,
            stride=args.stride,
            fps=args.fps,
            enable_padding=not args.no_padding,
        )

    print("\n" + "=" * 60)
    print("Cholec80 preprocessing complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
