app: vjepa_cpt
cpus_per_task: 4
folder: logs6/autolaparo_cpt_epoch-50_vitl16-256px-64f_lr1e-4_precise
mem_per_gpu: 220G
nodes: 1
tasks_per_node: 1
data:
  dataset_type: surgical_videodataset
  datasets:
  - data/Surge_Frames/AutoLaparo/clips_64f/train_dense_64f_detailed.csv
  datasets_weights:
  - 1.0
  batch_size: 128
  crop_size: 256
  dataset_fpcs:
  - 64
  fps: 1
  num_workers: 4
  patch_size: 16
  persistent_workers: true
  pin_mem: false
  tubelet_size: 2
data_aug:
  auto_augment: true
  motion_shift: true
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.25
loss:
  loss_exp: 1.0
mask:
- aspect_ratio:
  - 0.75
  - 1.5
  full_complement: false
  max_keep: null
  max_temporal_keep: 1.0
  num_blocks: 2
  spatial_scale:
  - 0.9
  - 0.9
  temporal_scale:
  - 1.0
  - 1.0
meta:
  dtype: bfloat16
  eval_freq: 100
  load_checkpoint: false
  read_checkpoint: None
  save_every_freq: 50
  seed: 239
  use_sdpa: true
model:
  model_name: vit_large
  pred_depth: 12
  pred_embed_dim: 384
  pred_num_heads: 12
  uniform_power: true
  use_activation_checkpointing: true
  use_mask_tokens: true
  use_rope: true
  zero_init_mask_tokens: true
  cpt_ckeckpoint: ckpts/vitl.pt 
optimization:
  anneal_ckpt: None
  ema:
  - 0.99925
  - 0.99925
  epochs: 50
  final_lr: 1.0e-07
  final_weight_decay: 0.04
  ipe: 300        # 1.9倍数据重复，但学习率调度正常
  ipe_scale: 1.0  # 确保学习率调度与实际训练步数匹配
  is_anneal: true
  lr: 1.0e-04
  resume_anneal: true
  start_lr: 0.0001
  warmup: 0
  weight_decay: 0.04
