cpus_per_task: 16
eval_name: surgical_video_classification_frozen
folder: logs2/pitvis_vitl16_16x2x3_96f_orgin_probing_1epochs_clean
mem_per_gpu: 220G
nodes: 8
max_workers: 8
resume_checkpoint: true
tag: ssv2-vitl16-16x2x3-16f
tasks_per_node: 8
experiment:
  classifier:
    num_heads: 16
    num_probe_blocks: 4
  data:
    dataset_type: surgical_videodataset
    dataset_train: /data/wjl/vjepa2/data_process/pitvis_clips_clean/pitvis_clips_clean_96f/train_dense_96f_detailed.csv
    dataset_val: /data/wjl/vjepa2/data_process/pitvis_clips_clean/pitvis_clips_clean_96f/val_dense_96f_detailed.csv
    frames_per_clip: 96
    num_classes: 15
    num_segments: 1
    num_views_per_segment: 1
    resolution: 256
  optimization:
    batch_size: 32
    multihead_kwargs:
    - final_lr: 0.0
      final_weight_decay: 0.8
      lr: 0.0001
      start_lr: 0.0001
      warmup: 0.0
      weight_decay: 0.8
    num_epochs: 1
    use_bfloat16: true
    use_pos_embed: false
model_kwargs:
  checkpoint: /data/wjl/vjepa2/ckpts/vitl.pt
  module_name: evals.video_classification_frozen.modelcustom.vit_encoder_multiclip
  pretrain_kwargs:
    encoder:
      checkpoint_key: target_encoder
      img_temporal_dim_size: null
      model_name: vit_large
      patch_size: 16
      tubelet_size: 2
      uniform_power: true
      use_rope: true
  wrapper_kwargs:
    max_frames: 128
    use_pos_embed: false
